INSERT INTO teams (id, name, city, stadium_id, conference, division) 
VALUES
('LAR', 'Rams', 'Los Angeles', 18, 'NFC', 'West'), 
('SEA', 'Seahawks', 'Seattle', 27, 'NFC', 'West'), 
('SFO', '49ers', 'San Fransisco', 26, 'NFC', 'West'), 
('ARI', 'Cardinals', 'Phoenix', 1, 'NFC', 'West'),  
('ATL', 'Falcons', 'Atlanta', 2, 'NFC', 'South'), 
('BAL', 'Ravens', 'Baltimore', 3, 'AFC', 'North'), 
('BUF', 'Bills', 'Buffalo', 4, 'AFC', 'East'), 
('CAR', 'Panthers', 'Carolina', 5, 'NFC', 'South'), 
('CHI', 'Bears', 'Chicago', 6, 'NFC', 'North'), 
('CIN', 'Bengals', 'Cincinnati', 7, 'AFC', 'North'), 
('CLE', 'Browns', 'Cleveland', 8, 'AFC', 'North'), 
('DAL', 'Cowboys', 'Dallas', 9, 'NFC', 'East'), 
('DEN', 'Broncos', 'Denver', 10, 'AFC', 'West'), 
('DET', 'Lions', 'Detroit', 11, 'NFC', 'North'), 
('GNB', 'Packers', 'Green Bay', 12, 'NFC', 'North'), 
('HOU', 'Texans', 'Houston', 13, 'AFC', 'South'), 
('IND', 'Colts', 'Indianapolis', 14, 'AFC', 'South'), 
('JAX', 'Jaguars', 'Jacksonville', 15, 'AFC', 'South'), 
('KAN', 'Chiefs', 'Kansas City', 16, 'AFC', 'West'), 
('LVR', 'Raiders', 'Las Vegas', 17, 'AFC', 'West'), 
('LAC', 'Chargers', 'Las Angeles', 18, 'AFC', 'West'), 
('MIA', 'Dolphins', 'Miami', 19, 'AFC', 'East'), 
('MIN', 'Vikings', 'Minnesota', 20, 'NFC', 'North'), 
('NWE', 'Patriots', 'New England', 21, 'AFC', 'East'), 
('NOR', 'Saints', 'New Orleans', 22, 'NFC', 'South'), 
('NYG', 'Giants', 'New York', 23, 'NFC', 'East'), 
('NYJ', 'Jets', 'New York', 23, 'AFC', 'East'), 
('PHI', 'Eagles', 'Philadelphia', 24, 'NFC', 'East'), 
('PIT', 'Steelers', 'Pittsburgh', 25, 'AFC', 'North'), 
('TAM', 'Buccaneers', 'Tampa Bay', 28, 'NFC', 'South'), 
('TEN', 'Titans', 'Tennesse', 29, 'AFC', 'South'), 
('WAS', 'Commanders', 'Washington', 30, 'NFC', 'East');